### ISSUE TITLE
add new logo to repo

### ISSUE THREAD

**Issue by hofmannv** [Materials-Data-Science-and-Informatics/somesy#60]
add new somesy logo (https://github.com/Materials-Data-Science-and-Informatics/Logos/tree/main/Somesy) for display into repo (e.g. readme)

**Comment by hofmannv** [comment]
also in https://helmholtz.software/software/somesy

**Comment by mustafasoylu** [comment]
@hofmannv 
I think Helmholtz software directly gets information from GitHub, so updating the repository would change Helmholtz software page too.
