### ISSUE TITLE
update record on zenodo.org

### ISSUE THREAD

**Issue by hofmannv** [Materials-Data-Science-and-Informatics/somesy#84]
just noticed (while checking on something else) that there was no repo dump of Somesy to Zenodo since v0.3.1 in January. Since two more releases and its v0.4.1 maybe you could update the record at some point.

Low priority, just noticed and had to write down somewhere...

**Comment by mustafasoylu** [comment]
I logged in to Zenodo and reactivated somesy integration. Including version 0.4.2, releases are automatically uploaded to zenodo again.

**Comment by mustafasoylu** [comment]
@hofmannv i checked it with new v0.4.3, it is uploaded, so i am closing this issue
